#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: 2.1

orbs:
  slack: circleci/slack@3.4.2

commands:
  slack_notification:
    description: "Notify about failure on Slack"
    steps:
      - slack/status:
          fail_only: true
          only_for_branches: master
          webhook: '${SLACK_WEBHOOK}'

jobs:
  daml_test:
    parameters:
      daml_sdk_version:
        type: string
    docker:
      - image: digitalasset/daml-sdk:<< parameters.daml_sdk_version >>
    steps:
      - checkout
      - run:
          name: Build Daml
          command: |
            daml build
      - run:
          name: Daml tests
          command: |
            daml test --junit target/daml-test-reports/model.xml
      - store_test_results:
          path: target/daml-test-reports
      - store_artifacts:
          path: target/daml-test-reports
      - slack_notification

workflows:
  version: 2
  test:
    jobs:
      - daml_test:
          daml_sdk_version: "0.13.32"
          context: refapps
  scheduled_test:
    triggers:
      - schedule:
          # need to scatter jobs to reduce Blackduck load
          # see also https://digitalasset.atlassian.net/browse/ERA-913
          cron: "0 6* * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - daml_test:
          daml_sdk_version: "0.13.32"
          context: refapps
